name: build-pkg

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: NodeJS setup
      uses: actions/setup-node@v2
      with:
        node-version: "12"
    - name: Install NodeJS dependencies
      run: |
        npm install
        npm run build
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build Python package
      run: |
        python setup.py sdist bdist_wheel
